'use client';

import { useAppStore } from '@/store/useAppStore';
import { formatCO2 } from '@/lib/calculations';
import { BREAKDOWN_LABELS, BREAKDOWN_ICONS } from '@/lib/constants';

export function ShareTemplate() {
  const { currentResult } = useAppStore();

  if (!currentResult) return null;

  const monthlyTotal = currentResult.total / 12;

  return (
    <div
      id="ecotrace-share"
      className="bg-gray-900 p-8 rounded-2xl max-w-md mx-auto"
      style={{ fontFamily: 'Inter, system-ui, sans-serif' }}
    >
      <div className="text-center mb-6">
        <div className="flex items-center justify-center gap-2 mb-2">
          <span className="text-3xl">🌍</span>
          <h1 className="text-2xl font-bold text-white">EcoTrace</h1>
        </div>
        <p className="text-white/60 text-sm">My Carbon Footprint Report</p>
      </div>

      <div className="bg-gradient-to-br from-eco-500/20 to-eco-600/20 rounded-xl p-6 mb-6 text-center border border-eco-500/30">
        <p className="text-white/60 text-sm mb-1">Annual Carbon Footprint</p>
        <p className="text-4xl font-bold text-eco-400">{formatCO2(currentResult.total)}</p>
        <p className="text-white/60 text-sm mt-1">{formatCO2(monthlyTotal)}/month</p>
      </div>

      <div className="grid grid-cols-3 gap-3 mb-6">
        <div className="bg-white/5 rounded-lg p-3 text-center">
          <p className="text-lg font-bold text-white">{currentResult.treesNeeded}</p>
          <p className="text-xs text-white/50">Trees Needed</p>
        </div>
        <div className="bg-white/5 rounded-lg p-3 text-center">
          <p className="text-lg font-bold text-white">{currentResult.dailyAverage.toFixed(1)}</p>
          <p className="text-xs text-white/50">kg CO₂/Day</p>
        </div>
        <div className="bg-white/5 rounded-lg p-3 text-center">
          <p className="text-lg font-bold text-eco-400">
            {currentResult.comparedToWorld > 0 ? '-' : '+'}
            {Math.abs(Math.round(currentResult.comparedToWorld))}%
          </p>
          <p className="text-xs text-white/50">vs World Avg</p>
        </div>
      </div>

      <div className="space-y-2 mb-6">
        <p className="text-sm font-semibold text-white/80">Breakdown by Category</p>
        {Object.entries(currentResult.breakdown).map(([category, value]) => (
          <div key={category} className="flex items-center justify-between text-sm">
            <div className="flex items-center gap-2">
              <span>{BREAKDOWN_ICONS[category as keyof typeof BREAKDOWN_ICONS]}</span>
              <span className="text-white/70">{BREAKDOWN_LABELS[category as keyof typeof BREAKDOWN_LABELS]}</span>
            </div>
            <span className="text-white/90 font-medium">{formatCO2(value)}</span>
          </div>
        ))}
      </div>

      <div className="text-center pt-4 border-t border-white/10">
        <p className="text-xs text-white/40">
          Generated by EcoTrace • ecotrace.vercel.app
        </p>
        <p className="text-xs text-white/40 mt-1">
          {new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
      </div>
    </div>
  );
}
